#pragma once

#define MULTISCATTERING_LUT_ATMOSPHERE_ARGS     0
#define MULTISCATTERING_LUT_TRANSMITTANCE_INPUT 1
#define MULTISCATTERING_LUT_SAMPLER             2
#define MULTISCATTERING_LUT_OUTPUT              3
