#!/usr/bin/env python3
"""
embed_fast_noise.py

Build-time packer: reads EA's FAST-noise PNG slices and emits a C++
header + cpp pair containing the raw RG8 byte data of a 128x128x32 array.
Embedded into d3d9.dll at link time so we don't ship a separate file.

Usage:
  python embed_fast_noise.py <input_dir> <output_header> <output_cpp>
"""
import re
import sys
from pathlib import Path
from PIL import Image

WIDTH = 128
HEIGHT = 128
SLICES = 32
CHANNELS = 2  # RG8

# Extracts the trailing integer slice index from EA's filename pattern,
# e.g. "vector2_uniform_gauss1_0_Gauss10_separate05_17.png" -> 17.
_SLICE_NUM_RE = re.compile(r'_(\d+)\.png$', re.IGNORECASE)

def slice_index(path: Path) -> int:
    m = _SLICE_NUM_RE.search(path.name)
    if not m:
        sys.exit(f"cannot extract slice index from {path.name}")
    return int(m.group(1))

def main(in_dir: Path, out_h: Path, out_cpp: Path) -> None:
    png_paths = sorted(in_dir.glob("*.png"), key=slice_index)
    if len(png_paths) != SLICES:
        sys.exit(f"expected {SLICES} PNGs in {in_dir}, found {len(png_paths)}")

    # Sanity check: indices must be exactly 0..31, no gaps, no duplicates.
    indices = [slice_index(p) for p in png_paths]
    if indices != list(range(SLICES)):
        sys.exit(f"slice indices not 0..{SLICES-1}: got {indices}")

    data = bytearray()
    for p in png_paths:
        img = Image.open(p).convert("RGBA")
        if img.size != (WIDTH, HEIGHT):
            sys.exit(f"{p}: expected {WIDTH}x{HEIGHT}, got {img.size}")
        px = img.load()
        for y in range(HEIGHT):
            for x in range(WIDTH):
                r, g, _b, _a = px[x, y]
                data.append(r)
                data.append(g)

    expected = WIDTH * HEIGHT * SLICES * CHANNELS
    if len(data) != expected:
        sys.exit(f"data size {len(data)} != expected {expected}")

    # Banner reused for both generated files. Carries EA attribution so
    # the embedded data's provenance is documented in source.
    banner = (
        "// Generated by scripts/embed_fast_noise.py - DO NOT EDIT\n"
        "//\n"
        "// Embedded data: 128x128x32 RG8 noise vendored from EA's\n"
        "// importance-sampled-FAST-noise repository:\n"
        "// https://github.com/electronicarts/importance-sampled-FAST-noise\n"
        "//\n"
        "// Copyright (c) 2025 Electronic Arts Inc. All rights reserved.\n"
        "// Used under the BSD-3-Clause-variant license in\n"
        "// data/ea-fast-noise/LICENSE.txt.\n"
    )

    # Header
    out_h.parent.mkdir(parents=True, exist_ok=True)
    out_h.write_text(f"""{banner}#pragma once
#include <cstdint>

namespace dxvk {{
namespace rtxFastNoise {{
  constexpr uint32_t kWidth    = {WIDTH};
  constexpr uint32_t kHeight   = {HEIGHT};
  constexpr uint32_t kSlices   = {SLICES};
  constexpr uint32_t kChannels = {CHANNELS};
  constexpr size_t   kDataSize = kWidth * kHeight * kSlices * kChannels;
  extern const uint8_t kData[kDataSize];
}}
}}
""")

    # Cpp body - emit as 16-byte rows for readability
    lines = [banner.rstrip("\n"),
             f"#include \"{out_h.name}\"",
             "",
             "namespace dxvk {",
             "namespace rtxFastNoise {",
             "const uint8_t kData[kDataSize] = {"]
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += ["};", "}", "}", ""]
    out_cpp.write_text("\n".join(lines))

if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit("usage: embed_fast_noise.py <input_dir> <output_header> <output_cpp>")
    main(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))
